interfaces:
  interface:
  - name: ge-0/0/0
    unit:
    - name: '1'
      vlan_id: '1'
    vlan_tagging: true
  - name: ge-0/0/1
    unit:
    - name: '1'
      vlan_id: '1'
    vlan_tagging: true
  - name: fxp0
    unit:
    - name: '0'
      description: '*** management ***'
security:
  log:
    report: ''
    mode: stream
  screen:
    ids_option:
    - name: untrust-screen
      icmp:
        ping_death: true
      ip:
        source_route_option: true
        tear_drop: true
      tcp:
        syn_flood:
          alarm_threshold: '1024'
          attack_threshold: '200'
          source_threshold: '1024'
          destination_threshold: '2048'
          undocumented:
            queue_size: '2000'
          timeout: '20'
        land: true
  zones:
    security_zone:
    - name: trust
      host_inbound_traffic:
        system_services:
        - name: all
        protocols:
        - name: all
      tcp_rst: true
    - name: untrust
      screen: untrust-screen
    - name: VRF_10001
      interfaces:
      - name: ge-0/0/0.1
      - name: ge-0/0/1.1
      host_inbound_traffic:
        system_services:
        - name: all
        protocols:
        - name: all
policy_options:
  policy_statement:
  - name: ospf-default
    term:
    - name: '1'
      from:
        route_filter:
        - address: 0.0.0.0/0
          exact: true
          accept: true
routing_instances:
  instance:
  - instance_type: virtual-router
    protocols:
      ospf:
        area:
        - name: 0.0.0.0
          interface:
          - name: ge-0/0/0.1
          - name: ge-0/0/1.1
        export:
        - ospf-default
    name: fabric
    routing_options:
      static:
        route:
        - name: 0.0.0.0/0
          discard: true
    interface:
    - name: ge-0/0/0.1
    - name: ge-0/0/1.1
system:
  syslog:
    file:
    - contents:
      - any: true
        name: any
      name: messages
  license:
    autoupdate:
      url:
      - name: https://ae1.juniper.net/junos/key_retrieval
version: 18.2R3.4
_merge_directive: merge_recursive
