interfaces:
  interface:
  - unit:
    - name: '0'
    name: xe-0/0/0
  - name: xe-0/0/1
  - name: xe-0/0/2
  - name: xe-0/0/3
  - name: xe-0/0/4
  - name: em0
    unit:
    - description: '*** management ***'
      name: '0'
  - name: em1
    unit:
    - description: '*** to pfe ***'
      family:
        inet:
          address:
          - name: 169.254.0.2/24
      name: '0'
  - name: lo0
    unit:
    - description: '*** loopback ***'
      name: '0'
protocols:
  bgp:
    group:
    - name: EVPN_iBGP
      multipath: ''
      type: internal
      family:
        evpn:
          signaling: ''
    - vpn_apply_export: true
      import:
      - IPCLOS_BGP_IMP
      name: IPCLOS_eBGP
      multipath:
        multiple_as: true
      type: external
      bfd_liveness_detection:
        multiplier: '3'
        minimum_interval: '1000'
      export:
      - IPCLOS_BGP_EXP
      mtu_discovery: true
  igmp_snooping:
    vlan:
    - name: default
policy_options:
  policy_statement:
  - name: IPCLOS_BGP_EXP
    term:
    - name: loopback
      then:
        accept: true
      from:
        protocol:
        - direct
        - bgp
    - name: default
      then:
        reject: true
  - name: IPCLOS_BGP_IMP
    term:
    - from:
        protocol:
        - bgp
        - direct
      name: loopback
      then:
        accept: true
    - name: default
      then:
        reject: true
  - name: PFE-LB
    then:
      load_balance:
        per_packet: true
forwarding_options:
  storm_control_profiles:
  - all: ''
    name: default
routing_options:
  forwarding_table:
    ecmp_fast_reroute: true
    export:
    - PFE-LB
system:
  extensions:
    providers:
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: juniper
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: chef
  syslog:
    file:
    - contents:
      - notice: true
        name: any
      name: messages
version: 18.1R3-S5.3
_merge_directive: merge_recursive
