interfaces: {}
chassis:
  aggregated_devices:
    ethernet:
      device_count: '24'
snmp:
  community:
  - authorization: read-only
    name: public
  location: JCL Labs
  contact: aburston@juniper.net
protocols:
  lldp:
    interface:
    - name: all
policy_options: {}
routing_options:
  static:
    route:
    - name: 0.0.0.0/0
      next_hop:
      - 100.123.0.1
system:
  services:
    extension_service:
      notification:
        allow_clients:
          address:
          - 0.0.0.0/0
      request_response:
        grpc:
          undocumented:
            skip_authentication: null
          max_connections: '30'
    netconf:
      ssh: ''
    rest:
      http:
        port: '3000'
      enable_explorer: true
    ssh:
      root_login: allow
  syslog:
    user:
    - contents:
      - emergency: true
        name: any
      name: '*'
    file:
    - name: messages
      contents:
      - name: any
      - name: authorization
        info: true
    - name: interactive-commands
      contents:
      - any: true
        name: interactive-commands
  root_authentication:
    encrypted_password: $1$DbZ1Q3pj$s48cZytjsmSJRUJAf4LdM.
  login:
    user:
    - authentication:
        encrypted_password: $1$a31gJmWG$h9ohikT1ajySf/tVH.gmv1
      class: super-user
      name: jcluser
      uid: '2000'
    message: '***********************************************************************\nThis
      system is restricted to __________, authorized users for legitimate\nbusiness
      purposes only. All activity on the system will be logged and\nis subject to
      monitoring. Unauthorized access, use or modification\nof computers, data therein
      or data in transit to or from the computers\nis a violation of state and federal
      laws. Unauthorized activity will\nbe reported to the law enforcement for investigation
      and possible\nprosecution. __________ reserves the right to investigate, refer
      for\nprosecution and pursue monetary damages in civil actions in the event\nof
      unauthorized access.\n***********************************************************************\n'
_merge_directive: merge_recursive
