policy_options: {}
protocols:
  lldp:
    interface:
    - name: all
snmp:
  community:
  - authorization: read-only
    name: public
  contact: aburston@juniper.net
  location: JCL Labs
interfaces: {}
system:
  login:
    user:
    - authentication:
        encrypted_password: $1$a31gJmWG$h9ohikT1ajySf/tVH.gmv1
      class: super-user
      name: jcluser
      uid: '2000'
    message: '***********************************************************************\nThis
      system is restricted to __________, authorized users for legitimate\nbusiness
      purposes only. All activity on the system will be logged and\nis subject to
      monitoring. Unauthorized access, use or modification\nof computers, data therein
      or data in transit to or from the computers\nis a violation of state and federal
      laws. Unauthorized activity will\nbe reported to the law enforcement for investigation
      and possible\nprosecution. __________ reserves the right to investigate, refer
      for\nprosecution and pursue monetary damages in civil actions in the event\nof
      unauthorized access.\n***********************************************************************\n'
  root_authentication:
    encrypted_password: $1$DbZ1Q3pj$s48cZytjsmSJRUJAf4LdM.
  syslog:
    file:
    - contents:
      - name: any
      - name: authorization
        info: true
      name: messages
    - contents:
      - any: true
        name: interactive-commands
      name: interactive-commands
    user:
    - contents:
      - emergency: true
        name: any
      name: '*'
  services:
    ssh:
      root_login: allow
    extension_service:
      request_response:
        grpc:
          max_connections: '30'
          undocumented:
            skip_authentication: null
      notification:
        allow_clients:
          address:
          - 0.0.0.0/0
    rest:
      http:
        port: '3000'
      enable_explorer: true
    netconf:
      ssh: ''
chassis:
  aggregated_devices:
    ethernet:
      device_count: '24'
routing_options:
  static:
    route:
    - name: 0.0.0.0/0
      next_hop:
      - 100.123.0.1
_merge_directive: merge_recursive
