interfaces:
  interface:
  - description: '*** to dc1-spine1 ***'
    unit:
    - name: '0'
    name: xe-0/0/0
  - description: '*** to dc1-spine2 ***'
    unit:
    - name: '0'
    name: xe-0/0/1
  - ether_options:
      ieee_802_3ad:
        bundle: ae0
    name: xe-0/0/2
  - esi:
      all_active: true
    unit:
    - name: '0'
    name: ae0
    aggregated_ether_options:
      lacp:
        active: true
        periodic: fast
  - name: em0
    unit:
    - description: '*** management ***'
      name: '0'
  - name: em1
    unit:
    - description: '*** to pfe ***'
      family:
        inet:
          address:
          - name: 169.254.0.2/24
      name: '0'
  - name: irb
    unit:
    - family:
        inet:
          address:
          - name: 10.1.1.1/24
      mac: 02:0a:01:01:01:18
      name: '1001'
    - family:
        inet:
          address:
          - name: 10.2.1.1/24
      mac: 02:0a:02:01:01:18
      name: '2001'
    - family:
        inet:
          address:
          - name: 10.3.1.1/24
      mac: 02:0a:03:01:01:18
      name: '3001'
  - name: lo0
    unit:
    - description: '*** loopback ***'
      name: '0'
    - description: Loopback for VXLAN control packets for VRF_10001
      name: '10001'
    - description: Loopback for VXLAN control packets for VRF_10002
      name: '10002'
    - description: Loopback for VXLAN control packets for VRF_10003
      name: '10003'
protocols:
  bgp:
    group:
    - neighbor:
      - name: 10.30.100.3
      - name: 10.30.100.4
      local_as:
        as_number: '65200'
      name: EVPN_iBGP
      multipath: ''
      type: internal
      family:
        evpn:
          signaling: ''
    - vpn_apply_export: true
      import:
      - IPCLOS_BGP_IMP
      mtu_discovery: true
      name: IPCLOS_eBGP
      multipath:
        multiple_as: true
      type: external
      export:
      - IPCLOS_BGP_EXP
      bfd_liveness_detection:
        multiplier: '3'
        minimum_interval: '1000'
  igmp_snooping:
    vlan:
    - name: default
  evpn:
    extended_vni_list:
    - all
    multicast_mode: ingress-replication
    default_gateway: do-not-advertise
    encapsulation: vxlan
policy_options:
  policy_statement:
  - name: EVPN_T5_EXPORT
    term:
    - from:
        protocol:
        - direct
      name: fm_direct
      then:
        accept: true
    - from:
        protocol:
        - static
      name: fm_static
      then:
        accept: true
    - from:
        protocol:
        - evpn
        route_filter:
        - address: 0.0.0.0/0
          prefix_length_range: /32-/32
      name: fm_v4_host
      then:
        accept: true
    - from:
        protocol:
        - evpn
        route_filter:
        - address: 0::0/0
          prefix_length_range: /128-/128
      name: fm_v6_host
      then:
        accept: true
  - name: IPCLOS_BGP_EXP
    term:
    - name: loopback
      then:
        accept: true
      from:
        protocol:
        - direct
        - bgp
    - name: default
      then:
        reject: true
  - name: IPCLOS_BGP_IMP
    term:
    - from:
        protocol:
        - bgp
        - direct
      name: loopback
      then:
        accept: true
    - name: default
      then:
        reject: true
  - name: PFE-LB
    then:
      load_balance:
        per_packet: true
forwarding_options:
  storm_control_profiles:
  - all: ''
    name: default
vlans:
  vlan:
  - l3_interface: irb.1001
    name: vlan_1001
    vlan_id: '1001'
    vxlan:
      vni: '1001'
  - l3_interface: irb.2001
    name: vlan_2001
    vlan_id: '2001'
    vxlan:
      vni: '2001'
  - l3_interface: irb.3001
    name: vlan_3001
    vlan_id: '3001'
    vxlan:
      vni: '3001'
routing_options:
  forwarding_table:
    export:
    - PFE-LB
    chained_composite_next_hop:
      ingress:
        evpn: true
    ecmp_fast_reroute: true
routing_instances:
  instance:
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      evpn:
        ip_prefix_routes:
          vni: '10001'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10001
    routing_options:
      auto_export: ''
    interface:
    - name: irb.1001
    - name: lo0.10001
    vrf_target:
      community: target:1:10001
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      evpn:
        ip_prefix_routes:
          vni: '10002'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10002
    routing_options:
      auto_export: ''
    interface:
    - name: irb.2001
    - name: lo0.10002
    vrf_target:
      community: target:1:10002
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      evpn:
        ip_prefix_routes:
          vni: '10003'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10003
    routing_options:
      auto_export: ''
    interface:
    - name: irb.3001
    - name: lo0.10003
    vrf_target:
      community: target:1:10003
switch_options:
  vtep_source_interface:
    interface_name: lo0.0
  vrf_target:
    auto: ''
    community: target:9999:9999
system:
  extensions:
    providers:
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: juniper
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: chef
  syslog:
    file:
    - contents:
      - notice: true
        name: any
      name: messages
version: 18.1R3-S5.3
_merge_directive: merge_recursive
