interfaces:
  interface:
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.132.2/30
      name: '0'
    name: xe-0/0/0
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.142.2/30
      name: '0'
    name: xe-0/0/1
  - unit:
    - family:
        inet:
          address:
          - name: 10.97.1.1/30
      name: '1'
    - family:
        inet:
          address:
          - name: 10.97.2.1/30
      name: '2'
    - family:
        inet:
          address:
          - name: 10.97.3.1/30
      name: '3'
    name: xe-0/0/2
  - unit:
    - family:
        inet:
          address:
          - name: 10.96.1.1/30
      name: '1'
    - family:
        inet:
          address:
          - name: 10.96.2.1/30
      name: '2'
    - family:
        inet:
          address:
          - name: 10.96.3.1/30
      name: '3'
    name: xe-0/0/3
  - unit:
    - family:
        inet:
          address:
          - name: 10.32.10.1/30
      name: '0'
    name: xe-0/0/4
  - unit:
    - family:
        inet:
          address:
          - name: 100.123.24.2/16
      name: '0'
    name: em0
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.100.2/32
      name: '0'
    - family:
        inet:
          address:
          - name: 10.40.100.2/32
      name: '10001'
    - family:
        inet:
          address:
          - name: 10.40.100.7/32
      name: '10002'
    - family:
        inet:
          address:
          - name: 10.40.100.12/32
      name: '10003'
    name: lo0
  _merge_list_directives:
    interface:
      _merge_directive: merge_by_key
      _merge_key: name
  _merge_directive: merge_recursive
policy_options:
  community:
  - members:
    - '65507:1'
    name: dc1-borderleaf2
  policy_statement:
  - term:
    - then:
        community:
        - add: true
          community_name: dc1-borderleaf2
      name: loopback
    name: IPCLOS_BGP_EXP
  _merge_list_directives:
    policy_statement:
      _merge_directive: merge_by_key
      _merge_key: name
  _merge_directive: merge_recursive
protocols:
  bgp:
    group:
    - local_address: 10.30.100.2
      name: WAN_OVERLAY_eBGP
    - cluster: 10.30.100.2
      local_address: 10.30.100.2
      name: EVPN_iBGP
    - local_as:
        as_number: '65507'
      neighbor:
      - description: EBGP peering to 10.30.132.1
        name: 10.30.132.1
        peer_as: '65501'
      - description: EBGP peering to 10.30.142.1
        name: 10.30.142.1
        peer_as: '65502'
      - description: EBGP peering to 10.32.10.2
        name: 10.32.10.2
        peer_as: '65400'
      name: IPCLOS_eBGP
    _merge_list_directives:
      group:
        _merge_directive: merge_by_key
        _merge_key: name
    _merge_directive: merge_recursive
  _merge_directive: merge_recursive
routing_instances:
  instance:
  - route_distinguisher:
      rd_type: 10.40.100.2:10001
    name: VRF_10001
  - route_distinguisher:
      rd_type: 10.40.100.7:10002
    name: VRF_10002
  - route_distinguisher:
      rd_type: 10.40.100.12:10003
    name: VRF_10003
  _merge_list_directives:
    instance:
      _merge_directive: merge_by_key
      _merge_key: name
  _merge_directive: merge_recursive
routing_options:
  router_id: 10.30.100.2
  _merge_directive: merge_recursive
switch_options:
  route_distinguisher:
    rd_type: 10.30.100.2:9999
    _merge_directive: merge_recursive
  _merge_directive: merge_recursive
system:
  host_name: dc1-borderleaf2
  syslog:
    file:
    - contents:
      - info: true
        name: authorization
      name: messages
    - contents:
      - any: true
        name: interactive-commands
      name: interactive-commands
    _merge_list_directives:
      file:
        _merge_directive: merge_by_key
        _merge_key: name
    _merge_directive: merge_recursive
  _merge_directive: merge_recursive
_merge_directive: merge_recursive
