interfaces:
  interface:
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.141.1/30
      name: '0'
    name: xe-0/0/0
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.142.1/30
      name: '0'
    name: xe-0/0/1
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.145.1/30
      name: '0'
    name: xe-0/0/2
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.146.1/30
      name: '0'
    name: xe-0/0/3
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.147.1/30
      name: '0'
    name: xe-0/0/4
  - unit:
    - family:
        inet:
          address:
          - name: 100.123.24.4/16
      name: '0'
    name: em0
  - unit:
    - family:
        inet:
          address:
          - name: 10.30.100.4/32
      name: '0'
    name: lo0
  _merge_list_directives:
    interface:
      _merge_directive: merge_by_key
      _merge_key: name
  _merge_directive: merge_recursive
policy_options:
  community:
  - members:
    - '65502:1'
    name: dc1-spine2
  policy_statement:
  - term:
    - then:
        community:
        - add: true
          community_name: dc1-spine2
      name: loopback
    name: IPCLOS_BGP_EXP
  _merge_list_directives:
    policy_statement:
      _merge_directive: merge_by_key
      _merge_key: name
  _merge_directive: merge_recursive
protocols:
  bgp:
    group:
    - cluster: 10.30.100.4
      local_address: 10.30.100.4
      neighbor:
      - name: 10.30.100.3
      name: EVPN_iBGP
    - local_as:
        as_number: '65502'
      neighbor:
      - description: EBGP peering to 10.30.145.2
        name: 10.30.145.2
        peer_as: '65503'
      - description: EBGP peering to 10.30.146.2
        name: 10.30.146.2
        peer_as: '65504'
      - description: EBGP peering to 10.30.147.2
        name: 10.30.147.2
        peer_as: '65505'
      - description: EBGP peering to 10.30.141.2
        name: 10.30.141.2
        peer_as: '65506'
      - description: EBGP peering to 10.30.142.2
        name: 10.30.142.2
        peer_as: '65507'
      name: IPCLOS_eBGP
    _merge_list_directives:
      group:
        _merge_directive: merge_by_key
        _merge_key: name
    _merge_directive: merge_recursive
  _merge_directive: merge_recursive
routing_options:
  router_id: 10.30.100.4
  _merge_directive: merge_recursive
system:
  host_name: dc1-spine2
  syslog:
    file:
    - contents:
      - info: true
        name: authorization
      name: messages
    - contents:
      - any: true
        name: interactive-commands
      name: interactive-commands
    _merge_list_directives:
      file:
        _merge_directive: merge_by_key
        _merge_key: name
    _merge_directive: merge_recursive
  _merge_directive: merge_recursive
_merge_directive: merge_recursive
