#!/usr/bin/env python3


import os
from importlib.resources import files, as_file

with as_file(files('jtaf_pyang_plugin').joinpath('__init__.py')) as init_py:
    package_dir = os.path.dirname(init_py)

print(f"{package_dir}")
