interfaces:
  interface:
  - description: '*** to dc1-spine1 ***'
    unit:
    - name: '0'
    name: xe-0/0/0
  - description: '*** to dc1-spine2 ***'
    unit:
    - name: '0'
    name: xe-0/0/1
  - name: xe-0/0/2
    unit:
    - name: '1'
      vlan_id: '1'
    - name: '2'
      vlan_id: '2'
    - name: '3'
      vlan_id: '3'
    vlan_tagging: true
  - name: xe-0/0/3
    unit:
    - name: '1'
      vlan_id: '1'
    - name: '2'
      vlan_id: '2'
    - name: '3'
      vlan_id: '3'
    vlan_tagging: true
  - description: '*** to wan-pe1 ***'
    unit:
    - name: '0'
    name: xe-0/0/4
  - name: em0
    unit:
    - description: '*** management ***'
      name: '0'
  - name: em1
    unit:
    - description: '*** to pfe ***'
      family:
        inet:
          address:
          - name: 169.254.0.2/24
      name: '0'
  - name: lo0
    unit:
    - description: '*** loopback ***'
      name: '0'
    - description: Loopback for VXLAN control packets for VRF_10001
      name: '10001'
    - description: Loopback for VXLAN control packets for VRF_10002
      name: '10002'
    - description: Loopback for VXLAN control packets for VRF_10003
      name: '10003'
protocols:
  bgp:
    group:
    - local_as:
        as_number: '65200'
      neighbor:
      - description: DCI EBGP peering to 10.30.100.8
        name: 10.30.100.8
        peer_as: '65201'
      - description: DCI EBGP peering to 10.30.100.9
        name: 10.30.100.9
        peer_as: '65201'
      multihop:
        no_nexthop_change: true
      name: WAN_OVERLAY_eBGP
      multipath:
        multiple_as: true
      type: external
      family:
        evpn:
          signaling:
            delay_route_advertisements:
              minimum_delay:
                routing_uptime: '480'
    - local_as:
        as_number: '65200'
      neighbor:
      - name: 10.30.100.3
      - name: 10.30.100.4
      name: EVPN_iBGP
      multipath: ''
      type: internal
      family:
        evpn:
          signaling: ''
    - vpn_apply_export: true
      import:
      - IPCLOS_BGP_IMP
      name: IPCLOS_eBGP
      bfd_liveness_detection:
        multiplier: '3'
        minimum_interval: '1000'
      multipath:
        multiple_as: true
      type: external
      export:
      - IPCLOS_BGP_EXP
      mtu_discovery: true
  igmp_snooping:
    vlan:
    - name: default
  evpn:
    multicast_mode: ingress-replication
    default_gateway: do-not-advertise
    encapsulation: vxlan
policy_options:
  policy_statement:
  - name: EVPN_T5_EXPORT
    term:
    - from:
        protocol:
        - direct
      name: fm_direct
      then:
        accept: true
    - from:
        protocol:
        - static
      name: fm_static
      then:
        accept: true
    - from:
        protocol:
        - evpn
        - ospf
        route_filter:
        - address: 0.0.0.0/0
          exact: true
      name: fm_v4_default
      then:
        accept: true
    - from:
        protocol:
        - evpn
        route_filter:
        - address: 0::0/0
          prefix_length_range: /128-/128
      name: fm_v6_host
      then:
        accept: true
  - name: IPCLOS_BGP_EXP
    term:
    - name: loopback
      then:
        accept: true
      from:
        protocol:
        - direct
        - bgp
    - name: default
      then:
        reject: true
  - name: IPCLOS_BGP_IMP
    term:
    - from:
        protocol:
        - bgp
        - direct
      name: loopback
      then:
        accept: true
    - name: default
      then:
        reject: true
  - name: PFE-LB
    then:
      load_balance:
        per_packet: true
  - name: to-ospf
    term:
    - from:
        protocol:
        - evpn
      name: '10'
      then:
        accept: true
    - name: '100'
      then:
        reject: true
forwarding_options:
  storm_control_profiles:
  - all: ''
    name: default
routing_options:
  forwarding_table:
    export:
    - PFE-LB
    chained_composite_next_hop:
      ingress:
        evpn: true
    ecmp_fast_reroute: true
routing_instances:
  instance:
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      ospf:
        area:
        - interface:
          - metric: '100'
            name: xe-0/0/2.1
          - metric: '200'
            name: xe-0/0/3.1
          name: 0.0.0.0
        export:
        - to-ospf
      evpn:
        ip_prefix_routes:
          vni: '10001'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10001
    routing_options:
      auto_export: ''
    interface:
    - name: xe-0/0/2.1
    - name: xe-0/0/3.1
    - name: lo0.10001
    vrf_target:
      community: target:1:10001
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      ospf:
        area:
        - interface:
          - metric: '100'
            name: xe-0/0/2.2
          - metric: '200'
            name: xe-0/0/3.2
          name: 0.0.0.0
        export:
        - to-ospf
      evpn:
        ip_prefix_routes:
          vni: '10002'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10002
    routing_options:
      auto_export: ''
    interface:
    - name: xe-0/0/2.2
    - name: xe-0/0/3.2
    - name: lo0.10002
    vrf_target:
      community: target:1:10002
  - vrf_table_label: ''
    instance_type: vrf
    protocols:
      ospf:
        area:
        - interface:
          - metric: '100'
            name: xe-0/0/2.3
          - metric: '200'
            name: xe-0/0/3.3
          name: 0.0.0.0
        export:
        - to-ospf
      evpn:
        ip_prefix_routes:
          vni: '10003'
          advertise: direct-nexthop
          export:
          - EVPN_T5_EXPORT
          encapsulation: vxlan
    name: VRF_10003
    routing_options:
      auto_export: ''
    interface:
    - name: xe-0/0/2.3
    - name: xe-0/0/3.3
    - name: lo0.10003
    vrf_target:
      community: target:1:10003
switch_options:
  vtep_source_interface:
    interface_name: lo0.0
  vrf_target:
    auto: ''
    community: target:9999:9999
system:
  extensions:
    providers:
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: juniper
    - license_type:
      - deployment_scope:
        - commercial
        name: juniper
      name: chef
  syslog:
    file:
    - contents:
      - notice: true
        name: any
      name: messages
version: 18.1R3-S5.3
_merge_directive: merge_recursive
